#!/bin/sh
#
# Time-stamp: <File deploy saved at 11:18:01 CEST on Tuesday 2018-07-31, by janjoris on sinclair.>
#

REPDIR=/remote/nfs1/data/rep/www.janjoris.nl
WWWDIR=/var/www/www.janjoris.nl

cd $REPDIR/root

# clean out WWWDIR

ssh wales.lan rm -rf $WWWDIR/\*

# make files globally readable

chmod -R u=rwX,go=rX .

# tar up and send to Wales

tar cz . | ssh wales.lan tar xvz --directory $WWWDIR

# restore permissions again

chmod -R u=rwX,g=rwX,o= .

