#!/bin/sh
#
# Time-stamp: <File deploy saved at 10:43:01 CEST on Tuesday 2018-07-31, by janjoris on sinclair.>
#

REPDIR=/remote/nfs1/data/rep/www.janjoris.nl
WWWDIR=/var/www/www.janjoris.nl

cd $REPDIR/root

chmod -R u=rwX,go=rX .

ssh wales.lan rm -rf $WWWDIR/\*

tar cz . | ssh wales.lan tar xvz --directory $WWWDIR
